"""
PropAI — Real Estate Investment Intelligence Platform
FastAPI Application Entry Point
"""

from __future__ import annotations

import os
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from api.underwriting import router as underwriting_router
from api.market import router as market_router
from api.ai import router as ai_router
from api.analysis import router as analysis_router


# ---------------------------------------------------------------------------
# App Lifecycle
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup and shutdown logic."""
    print("🏢 PropAI starting up...")
    yield
    print("🏢 PropAI shutting down.")


# ---------------------------------------------------------------------------
# App Configuration
# ---------------------------------------------------------------------------

app = FastAPI(
    title="PropAI",
    description="""
## PropAI — Real Estate Investment Intelligence Platform

An open-source AI copilot for real estate investment underwriting,
market research, and deal analysis.

### Features
- **Deal Underwriting** — Pro forma, DCF, IRR, NPV, Cap Rate, DSCR, equity multiple
- **Sensitivity Analysis** — 2D IRR and cash-on-cash sensitivity tables
- **Equity Waterfall** — LP/GP promote structures with multiple IRR hurdles
- **AI Investment Memos** — Institutional-quality memos generated by Claude
- **Market Research** — Census, FRED, HUD, and Zillow data integration

### Asset Classes Supported
SFR · Small Multifamily · Multifamily · Office · Retail · Mixed-Use ·
Industrial · Self-Storage · Short-Term Rental · Ground-Up Development

### Quick Start
```bash
POST /api/underwrite  →  Full underwriting (pro forma + sensitivity)
POST /api/underwrite/quick  →  Key metrics only (fast screening)
GET  /api/underwrite/sample  →  Sample deal input
GET  /api/underwrite/sample/result  →  Sample computed result
```
    """,
    version="0.1.0",
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc",
)

# ---------------------------------------------------------------------------
# CORS
# ---------------------------------------------------------------------------

ALLOWED_ORIGINS = os.getenv(
    "ALLOWED_ORIGINS",
    "http://localhost:3000,http://localhost:5173"
).split(",")

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Routers
# ---------------------------------------------------------------------------

app.include_router(underwriting_router)
app.include_router(market_router)
app.include_router(ai_router)
app.include_router(analysis_router)

# ---------------------------------------------------------------------------
# Root
# ---------------------------------------------------------------------------

@app.get("/", tags=["root"])
async def root():
    return {
        "name": "PropAI",
        "version": "0.1.0",
        "docs": "/docs",
        "status": "operational",
    }


@app.get("/health", tags=["root"])
async def health():
    return {"status": "healthy"}


# ---------------------------------------------------------------------------
# Entry Point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=int(os.getenv("PORT", "8000")),
        reload=os.getenv("ENV", "development") == "development",
        log_level="info",
    )
